namespace Phonie.Models;

public sealed record SimulatorSnapshot(
    DateTimeOffset Timestamp,
    string Simulator,
    string AircraftTitle,
    double Latitude,
    double Longitude,
    double AltitudeFeet,
    double HeadingMagneticDegrees,
    double IndicatedAirspeedKnots,
    double GroundSpeedKnots,
    bool IsOnGround,
    double Com1ActiveMhz,
    double Com1StandbyMhz,
    string Com1StationIdent,
    string Com1StationType,
    int Com1SpacingMode,
    bool Com1Receiving,
    int Com1Status,
    string TransponderCode,
    double DistanceToLfbiNm,
    double WindDirectionTrueDegrees,
    double WindVelocityKnots,
    double QnhHpa,
    double TemperatureCelsius,
    double VisibilityMeters);
